### PR TITLE
Filter by Category & Search From Styling to Functionality 

### LINKED ISSUE #26: Add Filter to Item Listed By Category
**Task title**
Add Filter to Item Listed By Category. 

**Task description**
- [x] Add New Component with it's Design For Categories .
- [x] Add Competent Listed Item 
- [x] Make Them dynamic So What Ever in DB Show there .
- [x] Add Functionality Any  Category I Click it Does Show Change The Content of The Cards.
- [x] Add Functionality For Search with it's Desgin
**Screenshots**
Capture

Figma Link

[Click here](https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?node-id=10-3&t=xaBU6ZMsJIYHyZDe-0)

### PR DESCRIPTION
**Pull request by YassinAbdulrahman**
Filter by Category & Search From Styling to Functionality .

Desktop View

Capture

Mobile View

FirstWorkMobile

### CODE REVIEW

**Comment by SarahSalem-hub** [comment]
@YassinAbdulrahman  there're a problem in test, you may want to update the snapshot again
`npm test -- -u   or yarn test -- -u`

and then push the updated file

**Comment by YassinAbdulrahman** [comment]
> @YassinAbdulrahman there're a problem in test, you may want to update the snapshot again `npm test -- -u or yarn test -- -u`
> 
> and then push the updated file

It was bug On The code was not Showing up When I go to Console I saw it And Fixed It Now Ready To Merge .

**Comment by SarahSalem-hub** [comment]
ok, thank you so much, I'll open it first to see the files structure before merging

**Comment by YassinAbdulrahman** [comment]
> ok, thank you so much, I'll open it first to see the files structure before merging

Take your Time ,,, Lmk if there is anything I can do it to update it

**Pull request merged**
